name: Build APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Instalar CLI de React Native (solo para esta compilación)
        run: npm install --no-save @react-native-community/cli

      - name: Crear carpeta de assets
        run: mkdir -p android/app/src/main/assets

      - name: Generar el bundle JS
        run: |
          node ./node_modules/react-native/cli.js bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/

      - name: Compilar APK de debug
        run: cd android && ./gradlew assembleDebug

      - name: Guardar APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
